import React from "react";
import ReactDOM from "react-dom";
import { createServer } from "miragejs";
import { App } from "./App";

createServer({
  routes() {
    this.namespace = "api";

    this.get("/transactions", () => {
      return [
        {
          id: 1,
          date: "10/10/2021",
          description: "Luz",
          category: "Lazer",
          type: "outcome",
          amount: 5104,
        },
        {
          id: 2,
          date: "23/09/2021",
          description: "Impostos",
          category: "Gastos esporádicos",
          type: "outcome",
          amount: 26469,
        },
        {
          id: 3,
          date: "26/08/2021",
          description: "Cabelo",
          category: "Alimentação",
          type: "outcome",
          amount: 17401,
        },
        {
          id: 4,
          date: "03/11/2021",
          description: "Pet",
          category: "Gastos esporádicos",
          type: "income",
          amount: 17487,
        },
        {
          id: 5,
          date: "23/12/2020",
          description: "Lanche",
          category: "Saúde",
          type: "income",
          amount: 16914,
        },
        {
          id: 6,
          date: "26/08/2021",
          description: "Cabelo",
          category: "Receita",
          type: "income",
          amount: 8446,
        },
        {
          id: 7,
          date: "09/09/2021",
          description: "Carro",
          category: "Receita",
          type: "outcome",
          amount: 19758,
        },
        {
          id: 8,
          date: "05/03/2021",
          description: "Mercado",
          category: "Saúde",
          type: "income",
          amount: 26104,
        },
        {
          id: 9,
          date: "05/03/2021",
          description: "Aluguel",
          category: "Saúde",
          type: "outcome",
          amount: 6793,
        },
        {
          id: 10,
          date: "11/07/2021",
          description: "Mercado",
          category: "Alimentação",
          type: "outcome",
          amount: 28313,
        },
        {
          id: 11,
          date: "21/05/2021",
          description: "Cabelo",
          category: "Gastos pessoais",
          type: "outcome",
          amount: 21196,
        },
        {
          id: 12,
          date: "16/08/2021",
          description: "Comida",
          category: "Gastos pessoais",
          type: "outcome",
          amount: 8422,
        },
        {
          id: 13,
          date: "22/04/2021",
          description: "Lanche",
          category: "Transporte",
          type: "outcome",
          amount: 27343,
        },
        {
          id: 14,
          date: "25/01/2021",
          description: "Cabelo",
          category: "Lazer",
          type: "outcome",
          amount: 25838,
        },
        {
          id: 15,
          date: "23/05/2021",
          description: "Impostos",
          category: "Lazer",
          type: "outcome",
          amount: 14119,
        },
        {
          id: 16,
          date: "29/10/2021",
          description: "Roupa",
          category: "Saúde",
          type: "outcome",
          amount: 1052,
        },
        {
          id: 17,
          date: "26/10/2021",
          description: "Lanche",
          category: "Gastos esporádicos",
          type: "income",
          amount: 3188,
        },
        {
          id: 18,
          date: "25/04/2021",
          description: "Comida",
          category: "Lazer",
          type: "income",
          amount: 18487,
        },
        {
          id: 19,
          date: "17/11/2020",
          description: "Filhos",
          category: "Transporte",
          type: "income",
          amount: 2545,
        },
        {
          id: 20,
          date: "22/08/2021",
          description: "Estudos",
          category: "Lazer",
          type: "outcome",
          amount: 24530,
        },
        {
          id: 21,
          date: "04/12/2020",
          description: "Internet",
          category: "Gastos esporádicos",
          type: "outcome",
          amount: 9954,
        },
        {
          id: 22,
          date: "14/08/2021",
          description: "Roupa",
          category: "Estudos",
          type: "outcome",
          amount: 20228,
        },
        {
          id: 23,
          date: "07/02/2021",
          description: "Mercado",
          category: "Alimentação",
          type: "income",
          amount: 29907,
        },
        {
          id: 24,
          date: "22/09/2021",
          description: "Comida",
          category: "Receita",
          type: "outcome",
          amount: 22902,
        },
        {
          id: 25,
          date: "11/08/2021",
          description: "Estudos",
          category: "Lazer",
          type: "income",
          amount: 14580,
        },
        {
          id: 26,
          date: "17/03/2021",
          description: "Dividendos",
          category: "Estudos",
          type: "outcome",
          amount: 7747,
        },
        {
          id: 27,
          date: "25/08/2021",
          description: "Roupa",
          category: "Gastos esporádicos",
          type: "income",
          amount: 1284,
        },
        {
          id: 28,
          date: "29/12/2020",
          description: "Impostos",
          category: "Saúde",
          type: "income",
          amount: 12034,
        },
        {
          id: 29,
          date: "04/12/2020",
          description: "Carro",
          category: "Estudos",
          type: "income",
          amount: 521,
        },
        {
          id: 30,
          date: "12/05/2021",
          description: "Pet",
          category: "Receita",
          type: "outcome",
          amount: 4977,
        },
      ];
    });
  },
});

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);
